---
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.1.231:9090', '192.168.1.220:9323', 'cadvisor:8080']
  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus.rsletten.com:9100', 'libvirt.rsletten.com:9100', 'zerocool.rsletten.com:9100']
